/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AccountService.as).
 */

package org.graniteds.tutorial.data.client.services;

import java.util.concurrent.Future;

import org.granite.client.tide.impl.ComponentImpl;
import org.granite.client.tide.server.ServerSession;
import org.granite.client.tide.server.TideResponder;
import org.granite.tide.data.model.Page;
import org.granite.tide.data.model.PageInfo;
import org.graniteds.tutorial.data.client.entities.Account;

///////////////////////////////////////////////////////////////////////////////
// Write Class Declaration.%>

public class AccountServiceBase extends ComponentImpl {
    
    public AccountServiceBase(ServerSession serverSession) {
    	super(serverSession);
    }    
    public Future<Page<Account>> findByFilter(Object arg0, PageInfo arg1, TideResponder<Page<Account>> tideResponder) {
		return super.call("findByFilter", arg0, arg1, tideResponder);
    }    
    public Future<Void> remove(Account arg0, TideResponder<Void> tideResponder) {
		return super.call("remove", arg0, tideResponder);
    }    
    public Future<Void> save(Account arg0, TideResponder<Void> tideResponder) {
		return super.call("save", arg0, tideResponder);
    }
}
