/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.graniteds.tutorial.data.services {

    [RemoteClass(alias="org.graniteds.tutorial.data.services.AccountService")]
    public class AccountService extends AccountServiceBase {

        public function AccountService() {
            super();
        }
    }
}
