/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.graniteds.tutorial.data.client;

import javax.inject.Named;
import javax.validation.Validation;
import javax.validation.Validator;

import org.granite.client.javafx.tide.ManagedEntity;
import org.granite.client.tide.server.TideResponders;


@Named
public class AccountController extends ManagedEntity<Account> {

	private final Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
	
	private AccountService accountService;
	
	public AccountController(AccountService accountService) {
		this.accountService = accountService;
	}
	
	
	public void save() {
        if (!validator.validate(getInstance()).isEmpty()) // <2>
            return;

        accountService.save(getInstance(), TideResponders.of(
            tre -> setInstance(null),
            tfe -> System.out.println("Could not save account: " + tfe.getFault())
        ));
	}
	
	public void remove() {
        accountService.remove(getInstance(), TideResponders.of(
        	tre -> setInstance(null),
        	tfe -> System.out.println("Could not delete account: " + tfe.getFault()
        )));
	}
}