/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
* *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Account.as).
 */

package org.graniteds.tutorial.data.client.entities;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import org.granite.client.persistence.Entity;
import org.granite.client.persistence.Id;
import org.granite.client.persistence.Uid;
import org.granite.client.persistence.Version;
import org.granite.messaging.annotations.Serialized;

@Entity
@Serialized(propertiesOrder={ "__initialized__", "__detachedState__", "email", "gravatarUrl", "id", "name", "phones", "uid", "version", "webSite" })
public class AccountBase implements Serializable {

    private static final long serialVersionUID = 1L;

    @SuppressWarnings("unused")
    private boolean __initialized__ = true;
    @SuppressWarnings("unused")
	private String __detachedState__ = null;
    
    @Id
    private Long id;
    @Uid
    private String uid;
    @Version
    private Long version;
    private String name;
    private Set<String> phones = new HashSet<String>();
    private String email;
    private String gravatarUrl;
    private String webSite;
    
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getUid() {
		return uid;
	}
	public void setUid(String uid) {
		this.uid = uid;
	}
	public Long getVersion() {
		return version;
	}
	public void setVersion(Long version) {
		this.version = version;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Set<String> getPhones() {
		return phones;
	}
	public void setPhones(Set<String> phones) {
		this.phones = phones;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getGravatarUrl() {
		return gravatarUrl;
	}
	public void setGravatarUrl(String gravatarUrl) {
		this.gravatarUrl = gravatarUrl;
	}
	public String getWebSite() {
		return webSite;
	}
	public void setWebSite(String webSite) {
		this.webSite = webSite;
	}
}
