== The EJB server application
:icons: font
:rootdir: ../../../..
:srcdir: {rootdir}/server-ejb/src
:modelsrcdir: {rootdir}/server-model/src

The server application is a simple EJB service which implements basic CRUD operations on user accounts
in an in-memory HSQL database. The updates on the persistent entities are dispatched to other clients though a
messaging destination.

The necessary configuration for GraniteDS consists in adding an annotated configuration class to trigger the startup
of GraniteDS (using a Servlet 3 container initializer behind the scenes):

[[server.destination]]
[source,java,indent=0]
.main/java/org/graniteds/tutorial/data/app/DataApplication.java
----
include::{srcdir}/main/java/org/graniteds/tutorial/data/app/DataApplication.java[tags=server-filter]
----
<1> The +ServerFilter+ annotation triggers GraniteDS initialization with a EJB configuration.
<2> The property +dataTopic+ annotated with +MessagingDestination+ indicates that we want to setup a messaging destination
with the name of the property. See the client usage <<client.destination,here>>. The properties +no-local+ and
+session-selector+ are necessary because we will be using this destination to dispatch updates on JPA entities and the
client does not need to receive its own updates.

It's then necessary to add an empty +META-INF/services-config.properties+ file to trigger the GraniteDS class scanner
which will detect the EJB classes. This is a simple marker file which indicates to GraniteDS where to look for and
prevent from scanning the whole classpath.

The data model is a standard JPA entity with a few particularities:

[source,java,indent=0]
.main/java/org/graniteds/tutorial/data/entities/Account.java
----
include::{modelsrcdir}/main/java/org/graniteds/tutorial/data/entities/Account.java[tags=entity]
----
<1> The +DataPublishListener+ entity listener tracks update events on the entity and should be used in conjunction with
the +@DataEnabled+ annotations on services (see below).
<2> The entity must be +Serializable+.
<3> It's recommended (though not mandatory) that the entity uses optimistic locking with a numeric +@Version+ property.
This is necessary for proper concurrent modifications detection.
<4> It's recommended (though again not mandatory) that the entity has a persistent +uid+ property which is not the database
primary key. The goal is to have a unique key on the entity instance during its full lifecycle (from the client to the
 service and the database, and back). Usually this +uid+ will be initialized by the client (it's handled automatically by
 the framework).
<5> Bean validation annotations can be used and will be propagated by the code generator to the client classes.
<6> The +@Include+ annotation can be used to specify computed properties which are not persistent but should be serialized
with the entity and will be evaluated on the server during serialization.

The service is a simple stateless EJB which implements the following interface:

[source,java,indent=0]
.main/java/org/graniteds/tutorial/data/services/AccountService.java
----
include::{modelsrcdir}/main/java/org/graniteds/tutorial/data/services/AccountService.java[tags=service]
----
<1> The service interface is annotated with +@RemoteDestination+ to enable remote access from the client.
<2> The service interface is annotated with +@DataEnabled+ to indicate GDS that it has to track and send updates made on entities
during the execution of service methods. Updates will be sent on the specified topic, here +dataTopic+.

Here is the EJB implementation:

[source,java,indent=0]
.main/java/org/graniteds/tutorial/data/services/AccountServiceBean.java
----
include::{srcdir}/main/java/org/graniteds/tutorial/data/services/AccountServiceBean.java[tags=service-impl]
----
<1> Note the use of +merge+ to apply the changes coming from the client which are detached entities.
<2> The method +findByFilter+ has a specific signature +Page(Map, PageInfo)+ and implements the necessary support for
server-side paging and sorting. See the class +AccountSearch+ for the actual implementation using the JPA Criteria API.
