/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.graniteds.tutorial.data.entities {

    [Bindable]
    [RemoteClass(alias="org.graniteds.tutorial.data.entities.Account")]
    public class Account extends AccountBase {

        public function Account() {
            super();
        } 
    }
}